2023-06-15 18:04:28,680 - INFO: Starting Hydrogen Torch v1.2.0
2023-06-15 18:04:28,751 - INFO: <pre>Thu Jun 15 18:04:28 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:1B.0 Off |                    0 |
| N/A   37C    P0    37W / 300W |      3MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
</pre>
2023-06-15 18:04:28,751 - INFO: Global random seed: 163831
2023-06-15 18:04:28,751 - INFO: Preparing the data...
2023-06-15 18:04:28,752 - INFO: Setting up cross-validation...
2023-06-15 18:04:28,773 - INFO: Running k-fold setup...
2023-06-15 18:04:28,790 - INFO: audio stats:   0%|          | 0/681 [00:00<?, ?it/s]
2023-06-15 18:04:29,691 - INFO: audio stats:  10%|9         | 68/681 [00:00<00:08, 75.50it/s]
2023-06-15 18:04:30,182 - INFO: audio stats:  20%|#9        | 136/681 [00:01<00:05, 103.14it/s]
2023-06-15 18:04:30,341 - INFO: audio stats:  30%|##9       | 204/681 [00:01<00:03, 157.75it/s]
2023-06-15 18:04:30,501 - INFO: audio stats:  40%|###9      | 272/681 [00:01<00:01, 209.80it/s]
2023-06-15 18:04:30,661 - INFO: audio stats:  50%|####9     | 340/681 [00:01<00:01, 256.83it/s]
2023-06-15 18:04:30,820 - INFO: audio stats:  60%|#####9    | 408/681 [00:02<00:00, 296.88it/s]
2023-06-15 18:04:30,994 - INFO: audio stats:  70%|######9   | 476/681 [00:02<00:00, 322.44it/s]
2023-06-15 18:04:31,154 - INFO: audio stats:  80%|#######9  | 544/681 [00:02<00:00, 349.20it/s]
2023-06-15 18:04:31,314 - INFO: audio stats:  90%|########9 | 612/681 [00:02<00:00, 369.59it/s]
2023-06-15 18:04:31,412 - INFO: audio stats: 100%|#########9| 680/681 [00:02<00:00, 432.35it/s]
2023-06-15 18:04:31,413 - INFO: audio stats: 100%|##########| 681/681 [00:02<00:00, 259.63it/s]
2023-06-15 18:04:31,416 - WARNING: Training data has long audio files. Median clip duration: 2 (s). Max clip duration: 360 (s).
2023-06-15 18:04:31,417 - INFO: Using most common (77%) sample_rate: 48000 (Hz)
2023-06-15 18:04:31,417 - INFO: Using chunk size: 60 (s)
2023-06-15 18:04:31,836 - INFO: Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
2023-06-15 18:04:31,907 - INFO: Converted input conv conv1 pretrained weights from 3 to 1 channel(s)
2023-06-15 18:04:37,474 - INFO: Preparing train and validation data
2023-06-15 18:04:37,474 - INFO: Loading train dataset...
2023-06-15 18:04:37,477 - INFO: Loading validation dataset...
2023-06-15 18:04:37,480 - INFO: Number of observations in train dataset: 681
2023-06-15 18:04:37,480 - INFO: Number of observations in validation dataset: 170
2023-06-15 18:04:37,486 - INFO: Epoch: 1 / 5
2023-06-15 18:04:37,487 - INFO: train loss:   0%|          | 0/42 [00:00<?, ?it/s]
2023-06-15 18:04:46,881 - INFO: train loss: 0.69:   5%|4         | 2/42 [00:09<03:07,  4.70s/it]
2023-06-15 18:04:47,694 - INFO: train loss: 0.68:  10%|9         | 4/42 [00:10<01:22,  2.17s/it]
2023-06-15 18:04:51,449 - INFO: train loss: 0.67:  14%|#4        | 6/42 [00:13<01:13,  2.04s/it]
2023-06-15 18:04:52,274 - INFO: train loss: 0.65:  19%|#9        | 8/42 [00:14<00:47,  1.40s/it]
2023-06-15 18:04:53,089 - INFO: train loss: 0.62:  24%|##3       | 10/42 [00:15<00:33,  1.04s/it]
2023-06-15 18:04:53,927 - INFO: train loss: 0.56:  29%|##8       | 12/42 [00:16<00:24,  1.21it/s]
2023-06-15 18:04:54,738 - INFO: train loss: 0.49:  33%|###3      | 14/42 [00:17<00:19,  1.45it/s]
2023-06-15 18:04:55,576 - INFO: train loss: 0.44:  38%|###8      | 16/42 [00:18<00:15,  1.66it/s]
2023-06-15 18:04:56,389 - INFO: train loss: 0.39:  43%|####2     | 18/42 [00:18<00:13,  1.84it/s]
2023-06-15 18:04:57,225 - INFO: train loss: 0.36:  48%|####7     | 20/42 [00:19<00:11,  1.98it/s]
2023-06-15 18:04:58,041 - INFO: train loss: 0.35:  52%|#####2    | 22/42 [00:20<00:09,  2.11it/s]
2023-06-15 18:04:58,852 - INFO: train loss: 0.35:  57%|#####7    | 24/42 [00:21<00:08,  2.20it/s]
2023-06-15 18:05:08,939 - INFO: train loss: 0.36:  62%|######1   | 26/42 [00:31<00:29,  1.84s/it]
2023-06-15 18:05:09,760 - INFO: train loss: 0.36:  67%|######6   | 28/42 [00:32<00:19,  1.41s/it]
2023-06-15 18:05:10,590 - INFO: train loss: 0.37:  71%|#######1  | 30/42 [00:33<00:13,  1.11s/it]
2023-06-15 18:05:11,428 - INFO: train loss: 0.36:  76%|#######6  | 32/42 [00:33<00:09,  1.11it/s]
2023-06-15 18:05:12,239 - INFO: train loss: 0.36:  81%|########  | 34/42 [00:34<00:06,  1.33it/s]
2023-06-15 18:05:24,783 - INFO: train loss: 0.35:  86%|########5 | 36/42 [00:47<00:14,  2.41s/it]
2023-06-15 18:05:25,603 - INFO: train loss: 0.35:  90%|######### | 38/42 [00:48<00:07,  1.81s/it]
2023-06-15 18:05:26,412 - INFO: train loss: 0.35:  95%|#########5| 40/42 [00:48<00:02,  1.39s/it]
2023-06-15 18:05:27,221 - INFO: train loss: 0.36: 100%|##########| 42/42 [00:49<00:00,  1.09s/it]
2023-06-15 18:05:27,221 - INFO: train loss: 0.36: 100%|##########| 42/42 [00:49<00:00,  1.18s/it]
2023-06-15 18:05:27,222 - INFO: Starting validation inference
2023-06-15 18:05:27,222 - INFO: validation progress:   0%|          | 0/11 [00:00<?, ?it/s]
2023-06-15 18:05:31,012 - INFO: validation progress:   9%|9         | 1/11 [00:03<00:37,  3.79s/it]
2023-06-15 18:05:31,310 - INFO: validation progress:  18%|#8        | 2/11 [00:04<00:15,  1.74s/it]
2023-06-15 18:05:31,592 - INFO: validation progress:  27%|##7       | 3/11 [00:04<00:08,  1.07s/it]
2023-06-15 18:05:31,875 - INFO: validation progress:  36%|###6      | 4/11 [00:04<00:05,  1.31it/s]
2023-06-15 18:05:32,158 - INFO: validation progress:  45%|####5     | 5/11 [00:04<00:03,  1.70it/s]
2023-06-15 18:05:32,441 - INFO: validation progress:  55%|#####4    | 6/11 [00:05<00:02,  2.06it/s]
2023-06-15 18:05:32,724 - INFO: validation progress:  64%|######3   | 7/11 [00:05<00:01,  2.39it/s]
2023-06-15 18:05:33,008 - INFO: validation progress:  73%|#######2  | 8/11 [00:05<00:01,  2.66it/s]
2023-06-15 18:05:33,291 - INFO: validation progress:  82%|########1 | 9/11 [00:06<00:00,  2.88it/s]
2023-06-15 18:05:33,573 - INFO: validation progress:  91%|######### | 10/11 [00:06<00:00,  3.06it/s]
2023-06-15 18:05:34,340 - INFO: validation progress: 100%|##########| 11/11 [00:07<00:00,  2.17it/s]
2023-06-15 18:05:34,342 - INFO: validation progress: 100%|##########| 11/11 [00:07<00:00,  1.55it/s]
2023-06-15 18:05:34,408 - INFO: Mean validation loss: 0.39533
2023-06-15 18:05:34,417 - INFO: Validation ROC_AUC: 0.63935
2023-06-15 18:05:34,430 - ERROR: Stratified random sampling error: 
Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 195, in resolve
    return self.resolvers[key]
  File "/usr/lib/python3.8/collections/__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.8/collections/__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'class_MG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 206, in resolve
    return self.temps[key]
KeyError: 'class_MG'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hydrogen_torch_cythonized/hydrogen_torch/src/utils/data_utils.py", line 276, in hydrogen_torch.src.utils.data_utils.stratified_sample_indices
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4111, in query
    res = self.eval(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4240, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/eval.py", line 350, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 811, in __init__
    self.terms = self.parse()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 830, in parse
    return self._visitor.visit(self.expr)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 421, in visit_Module
    return self.visit(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 424, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 723, in visit_Compare
    return self.visit(binop)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 549, in visit_Name
    return self.term_type(node.id, self.env, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 98, in __init__
    self._value = self._resolve_name()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 115, in _resolve_name
    res = self.env.resolve(self.local_name, is_local=self.is_local)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 211, in resolve
    raise UndefinedVariableError(key, is_local) from err
pandas.core.computation.ops.UndefinedVariableError: name 'class_MG' is not defined
2023-06-15 18:06:36,526 - INFO: Epoch: 2 / 5
2023-06-15 18:06:36,527 - INFO: train loss:   0%|          | 0/42 [00:00<?, ?it/s]
2023-06-15 18:06:38,638 - INFO: train loss: 0.35:   5%|4         | 2/42 [00:02<00:42,  1.06s/it]
2023-06-15 18:06:39,450 - INFO: train loss: 0.35:  10%|9         | 4/42 [00:02<00:25,  1.49it/s]
2023-06-15 18:06:40,262 - INFO: train loss: 0.35:  14%|#4        | 6/42 [00:03<00:19,  1.81it/s]
2023-06-15 18:06:41,073 - INFO: train loss: 0.35:  19%|#9        | 8/42 [00:04<00:16,  2.02it/s]
2023-06-15 18:06:41,885 - INFO: train loss: 0.35:  24%|##3       | 10/42 [00:05<00:14,  2.16it/s]
2023-06-15 18:06:42,699 - INFO: train loss: 0.35:  29%|##8       | 12/42 [00:06<00:13,  2.26it/s]
2023-06-15 18:06:43,528 - INFO: train loss: 0.35:  33%|###3      | 14/42 [00:07<00:12,  2.30it/s]
2023-06-15 18:06:44,339 - INFO: train loss: 0.35:  38%|###8      | 16/42 [00:07<00:11,  2.35it/s]
2023-06-15 18:06:45,150 - INFO: train loss: 0.35:  43%|####2     | 18/42 [00:08<00:10,  2.39it/s]
2023-06-15 18:06:45,961 - INFO: train loss: 0.35:  48%|####7     | 20/42 [00:09<00:09,  2.41it/s]
2023-06-15 18:06:46,772 - INFO: train loss: 0.35:  52%|#####2    | 22/42 [00:10<00:08,  2.43it/s]
2023-06-15 18:06:47,584 - INFO: train loss: 0.35:  57%|#####7    | 24/42 [00:11<00:07,  2.44it/s]
2023-06-15 18:06:58,815 - INFO: train loss: 0.35:  57%|#####7    | 24/42 [00:22<00:07,  2.44it/s]
2023-06-15 18:06:59,815 - INFO: train loss: 0.35:  62%|######1   | 26/42 [00:23<00:34,  2.14s/it]
2023-06-15 18:07:00,628 - INFO: train loss: 0.35:  67%|######6   | 28/42 [00:24<00:22,  1.62s/it]
2023-06-15 18:07:01,454 - INFO: train loss: 0.35:  71%|#######1  | 30/42 [00:24<00:15,  1.25s/it]
2023-06-15 18:07:02,267 - INFO: train loss: 0.35:  76%|#######6  | 32/42 [00:25<00:09,  1.00it/s]
2023-06-15 18:07:03,079 - INFO: train loss: 0.35:  81%|########  | 34/42 [00:26<00:06,  1.22it/s]
2023-06-15 18:07:03,917 - INFO: train loss: 0.35:  86%|########5 | 36/42 [00:27<00:04,  1.43it/s]
2023-06-15 18:07:04,725 - INFO: train loss: 0.35:  90%|######### | 38/42 [00:28<00:02,  1.64it/s]
2023-06-15 18:07:14,765 - INFO: train loss: 0.35:  95%|#########5| 40/42 [00:38<00:03,  1.93s/it]
2023-06-15 18:07:15,572 - INFO: train loss: 0.35: 100%|##########| 42/42 [00:39<00:00,  1.48s/it]
2023-06-15 18:07:15,573 - INFO: train loss: 0.35: 100%|##########| 42/42 [00:39<00:00,  1.08it/s]
2023-06-15 18:07:15,574 - INFO: Starting validation inference
2023-06-15 18:07:15,574 - INFO: validation progress:   0%|          | 0/11 [00:00<?, ?it/s]
2023-06-15 18:07:17,620 - INFO: validation progress:   9%|9         | 1/11 [00:02<00:20,  2.05s/it]
2023-06-15 18:07:17,910 - INFO: validation progress:  18%|#8        | 2/11 [00:02<00:09,  1.01s/it]
2023-06-15 18:07:18,194 - INFO: validation progress:  27%|##7       | 3/11 [00:02<00:05,  1.47it/s]
2023-06-15 18:07:18,476 - INFO: validation progress:  36%|###6      | 4/11 [00:02<00:03,  1.91it/s]
2023-06-15 18:07:18,759 - INFO: validation progress:  45%|####5     | 5/11 [00:03<00:02,  2.29it/s]
2023-06-15 18:07:19,041 - INFO: validation progress:  55%|#####4    | 6/11 [00:03<00:01,  2.60it/s]
2023-06-15 18:07:19,323 - INFO: validation progress:  64%|######3   | 7/11 [00:03<00:01,  2.85it/s]
2023-06-15 18:07:19,605 - INFO: validation progress:  73%|#######2  | 8/11 [00:04<00:00,  3.04it/s]
2023-06-15 18:07:19,887 - INFO: validation progress:  82%|########1 | 9/11 [00:04<00:00,  3.18it/s]
2023-06-15 18:07:20,170 - INFO: validation progress:  91%|######### | 10/11 [00:04<00:00,  3.28it/s]
2023-06-15 18:07:20,350 - INFO: validation progress: 100%|##########| 11/11 [00:04<00:00,  3.75it/s]
2023-06-15 18:07:20,352 - INFO: validation progress: 100%|##########| 11/11 [00:04<00:00,  2.30it/s]
2023-06-15 18:07:20,419 - INFO: Mean validation loss: 0.40549
2023-06-15 18:07:20,429 - INFO: Validation ROC_AUC: 0.58598
2023-06-15 18:07:20,438 - ERROR: Stratified random sampling error: 
Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 195, in resolve
    return self.resolvers[key]
  File "/usr/lib/python3.8/collections/__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.8/collections/__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'class_MG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 206, in resolve
    return self.temps[key]
KeyError: 'class_MG'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hydrogen_torch_cythonized/hydrogen_torch/src/utils/data_utils.py", line 276, in hydrogen_torch.src.utils.data_utils.stratified_sample_indices
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4111, in query
    res = self.eval(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4240, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/eval.py", line 350, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 811, in __init__
    self.terms = self.parse()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 830, in parse
    return self._visitor.visit(self.expr)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 421, in visit_Module
    return self.visit(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 424, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 723, in visit_Compare
    return self.visit(binop)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 549, in visit_Name
    return self.term_type(node.id, self.env, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 98, in __init__
    self._value = self._resolve_name()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 115, in _resolve_name
    res = self.env.resolve(self.local_name, is_local=self.is_local)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 211, in resolve
    raise UndefinedVariableError(key, is_local) from err
pandas.core.computation.ops.UndefinedVariableError: name 'class_MG' is not defined
2023-06-15 18:08:21,088 - INFO: Epoch: 3 / 5
2023-06-15 18:08:21,088 - INFO: train loss:   0%|          | 0/42 [00:00<?, ?it/s]
2023-06-15 18:08:22,935 - INFO: train loss: 0.35:   5%|4         | 2/42 [00:01<00:36,  1.08it/s]
2023-06-15 18:08:23,747 - INFO: train loss: 0.35:  10%|9         | 4/42 [00:02<00:23,  1.62it/s]
2023-06-15 18:08:34,225 - INFO: train loss: 0.35:  14%|#4        | 6/42 [00:13<01:38,  2.73s/it]
2023-06-15 18:08:35,038 - INFO: train loss: 0.35:  19%|#9        | 8/42 [00:13<01:01,  1.81s/it]
2023-06-15 18:08:35,864 - INFO: train loss: 0.35:  24%|##3       | 10/42 [00:14<00:41,  1.31s/it]
2023-06-15 18:08:36,676 - INFO: train loss: 0.35:  29%|##8       | 12/42 [00:15<00:30,  1.00s/it]
2023-06-15 18:08:37,515 - INFO: train loss: 0.34:  33%|###3      | 14/42 [00:16<00:22,  1.23it/s]
2023-06-15 18:08:38,328 - INFO: train loss: 0.34:  38%|###8      | 16/42 [00:17<00:17,  1.47it/s]
2023-06-15 18:08:39,140 - INFO: train loss: 0.34:  43%|####2     | 18/42 [00:18<00:14,  1.68it/s]
2023-06-15 18:08:39,951 - INFO: train loss: 0.34:  48%|####7     | 20/42 [00:18<00:11,  1.86it/s]
2023-06-15 18:08:40,764 - INFO: train loss: 0.34:  52%|#####2    | 22/42 [00:19<00:09,  2.01it/s]
2023-06-15 18:08:52,360 - INFO: train loss: 0.33:  57%|#####7    | 24/42 [00:31<00:37,  2.11s/it]
2023-06-15 18:08:53,182 - INFO: train loss: 0.33:  62%|######1   | 26/42 [00:32<00:25,  1.60s/it]
2023-06-15 18:09:04,539 - INFO: train loss: 0.33:  67%|######6   | 28/42 [00:43<00:39,  2.83s/it]
2023-06-15 18:09:05,410 - INFO: train loss: 0.33:  71%|#######1  | 30/42 [00:44<00:25,  2.11s/it]
2023-06-15 18:09:06,269 - INFO: train loss: 0.33:  76%|#######6  | 32/42 [00:45<00:16,  1.60s/it]
2023-06-15 18:09:07,116 - INFO: train loss: 0.33:  81%|########  | 34/42 [00:46<00:09,  1.25s/it]
2023-06-15 18:09:07,925 - INFO: train loss: 0.32:  86%|########5 | 36/42 [00:46<00:05,  1.01it/s]
2023-06-15 18:09:08,733 - INFO: train loss: 0.32:  90%|######### | 38/42 [00:47<00:03,  1.22it/s]
2023-06-15 18:09:09,542 - INFO: train loss: 0.32:  95%|#########5| 40/42 [00:48<00:01,  1.44it/s]
2023-06-15 18:09:10,350 - INFO: train loss: 0.31: 100%|##########| 42/42 [00:49<00:00,  1.65it/s]
2023-06-15 18:09:10,350 - INFO: train loss: 0.31: 100%|##########| 42/42 [00:49<00:00,  1.17s/it]
2023-06-15 18:09:10,351 - INFO: Starting validation inference
2023-06-15 18:09:10,351 - INFO: validation progress:   0%|          | 0/11 [00:00<?, ?it/s]
2023-06-15 18:09:12,424 - INFO: validation progress:   9%|9         | 1/11 [00:02<00:20,  2.07s/it]
2023-06-15 18:09:12,715 - INFO: validation progress:  18%|#8        | 2/11 [00:02<00:09,  1.02s/it]
2023-06-15 18:09:12,998 - INFO: validation progress:  27%|##7       | 3/11 [00:02<00:05,  1.46it/s]
2023-06-15 18:09:13,281 - INFO: validation progress:  36%|###6      | 4/11 [00:02<00:03,  1.90it/s]
2023-06-15 18:09:13,564 - INFO: validation progress:  45%|####5     | 5/11 [00:03<00:02,  2.28it/s]
2023-06-15 18:09:13,846 - INFO: validation progress:  55%|#####4    | 6/11 [00:03<00:01,  2.59it/s]
2023-06-15 18:09:14,128 - INFO: validation progress:  64%|######3   | 7/11 [00:03<00:01,  2.84it/s]
2023-06-15 18:09:14,410 - INFO: validation progress:  73%|#######2  | 8/11 [00:04<00:00,  3.03it/s]
2023-06-15 18:09:14,693 - INFO: validation progress:  82%|########1 | 9/11 [00:04<00:00,  3.18it/s]
2023-06-15 18:09:14,975 - INFO: validation progress:  91%|######### | 10/11 [00:04<00:00,  3.28it/s]
2023-06-15 18:09:15,155 - INFO: validation progress: 100%|##########| 11/11 [00:04<00:00,  3.75it/s]
2023-06-15 18:09:15,157 - INFO: validation progress: 100%|##########| 11/11 [00:04<00:00,  2.29it/s]
2023-06-15 18:09:15,216 - INFO: Mean validation loss: 0.40377
2023-06-15 18:09:15,226 - INFO: Validation ROC_AUC: 0.75119
2023-06-15 18:09:15,235 - ERROR: Stratified random sampling error: 
Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 195, in resolve
    return self.resolvers[key]
  File "/usr/lib/python3.8/collections/__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.8/collections/__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'class_MG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 206, in resolve
    return self.temps[key]
KeyError: 'class_MG'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hydrogen_torch_cythonized/hydrogen_torch/src/utils/data_utils.py", line 276, in hydrogen_torch.src.utils.data_utils.stratified_sample_indices
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4111, in query
    res = self.eval(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4240, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/eval.py", line 350, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 811, in __init__
    self.terms = self.parse()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 830, in parse
    return self._visitor.visit(self.expr)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 421, in visit_Module
    return self.visit(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 424, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 723, in visit_Compare
    return self.visit(binop)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 549, in visit_Name
    return self.term_type(node.id, self.env, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 98, in __init__
    self._value = self._resolve_name()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 115, in _resolve_name
    res = self.env.resolve(self.local_name, is_local=self.is_local)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 211, in resolve
    raise UndefinedVariableError(key, is_local) from err
pandas.core.computation.ops.UndefinedVariableError: name 'class_MG' is not defined
2023-06-15 18:10:15,990 - INFO: Epoch: 4 / 5
2023-06-15 18:10:15,990 - INFO: train loss:   0%|          | 0/42 [00:00<?, ?it/s]
2023-06-15 18:10:17,880 - INFO: train loss: 0.30:   5%|4         | 2/42 [00:01<00:37,  1.06it/s]
2023-06-15 18:10:18,695 - INFO: train loss: 0.31:  10%|9         | 4/42 [00:02<00:23,  1.59it/s]
2023-06-15 18:10:19,510 - INFO: train loss: 0.31:  14%|#4        | 6/42 [00:03<00:18,  1.90it/s]
2023-06-15 18:10:20,323 - INFO: train loss: 0.30:  19%|#9        | 8/42 [00:04<00:16,  2.08it/s]
2023-06-15 18:10:21,137 - INFO: train loss: 0.30:  24%|##3       | 10/42 [00:05<00:14,  2.20it/s]
2023-06-15 18:10:30,370 - INFO: train loss: 0.30:  29%|##8       | 12/42 [00:14<00:56,  1.87s/it]
2023-06-15 18:10:31,186 - INFO: train loss: 0.29:  33%|###3      | 14/42 [00:15<00:38,  1.39s/it]
2023-06-15 18:10:32,000 - INFO: train loss: 0.29:  38%|###8      | 16/42 [00:16<00:28,  1.08s/it]
2023-06-15 18:10:32,815 - INFO: train loss: 0.30:  43%|####2     | 18/42 [00:16<00:20,  1.15it/s]
2023-06-15 18:10:33,673 - INFO: train loss: 0.29:  48%|####7     | 20/42 [00:17<00:16,  1.36it/s]
2023-06-15 18:10:34,491 - INFO: train loss: 0.29:  52%|#####2    | 22/42 [00:18<00:12,  1.58it/s]
2023-06-15 18:10:35,303 - INFO: train loss: 0.29:  57%|#####7    | 24/42 [00:19<00:10,  1.77it/s]
2023-06-15 18:10:45,217 - INFO: train loss: 0.29:  62%|######1   | 26/42 [00:29<00:30,  1.90s/it]
2023-06-15 18:10:46,048 - INFO: train loss: 0.28:  67%|######6   | 28/42 [00:30<00:20,  1.45s/it]
2023-06-15 18:10:46,861 - INFO: train loss: 0.28:  71%|#######1  | 30/42 [00:30<00:13,  1.13s/it]
2023-06-15 18:10:47,697 - INFO: train loss: 0.28:  76%|#######6  | 32/42 [00:31<00:09,  1.09it/s]
2023-06-15 18:10:48,509 - INFO: train loss: 0.28:  81%|########  | 34/42 [00:32<00:06,  1.31it/s]
2023-06-15 18:10:58,844 - INFO: train loss: 0.28:  81%|########  | 34/42 [00:42<00:06,  1.31it/s]
2023-06-15 18:11:00,014 - INFO: train loss: 0.28:  86%|########5 | 36/42 [00:44<00:13,  2.26s/it]
2023-06-15 18:11:00,834 - INFO: train loss: 0.27:  90%|######### | 38/42 [00:44<00:06,  1.71s/it]
2023-06-15 18:11:01,644 - INFO: train loss: 0.28:  95%|#########5| 40/42 [00:45<00:02,  1.32s/it]
2023-06-15 18:11:02,454 - INFO: train loss: 0.27: 100%|##########| 42/42 [00:46<00:00,  1.04s/it]
2023-06-15 18:11:02,455 - INFO: train loss: 0.27: 100%|##########| 42/42 [00:46<00:00,  1.11s/it]
2023-06-15 18:11:02,456 - INFO: Starting validation inference
2023-06-15 18:11:02,456 - INFO: validation progress:   0%|          | 0/11 [00:00<?, ?it/s]
2023-06-15 18:11:04,474 - INFO: validation progress:   9%|9         | 1/11 [00:02<00:20,  2.02s/it]
2023-06-15 18:11:04,758 - INFO: validation progress:  18%|#8        | 2/11 [00:02<00:08,  1.00it/s]
2023-06-15 18:11:05,042 - INFO: validation progress:  27%|##7       | 3/11 [00:02<00:05,  1.49it/s]
2023-06-15 18:11:05,325 - INFO: validation progress:  36%|###6      | 4/11 [00:02<00:03,  1.93it/s]
2023-06-15 18:11:05,608 - INFO: validation progress:  45%|####5     | 5/11 [00:03<00:02,  2.31it/s]
2023-06-15 18:11:05,890 - INFO: validation progress:  55%|#####4    | 6/11 [00:03<00:01,  2.62it/s]
2023-06-15 18:11:06,173 - INFO: validation progress:  64%|######3   | 7/11 [00:03<00:01,  2.86it/s]
2023-06-15 18:11:06,455 - INFO: validation progress:  73%|#######2  | 8/11 [00:03<00:00,  3.05it/s]
2023-06-15 18:11:06,738 - INFO: validation progress:  82%|########1 | 9/11 [00:04<00:00,  3.19it/s]
2023-06-15 18:11:07,020 - INFO: validation progress:  91%|######### | 10/11 [00:04<00:00,  3.29it/s]
2023-06-15 18:11:07,200 - INFO: validation progress: 100%|##########| 11/11 [00:04<00:00,  3.76it/s]
2023-06-15 18:11:07,202 - INFO: validation progress: 100%|##########| 11/11 [00:04<00:00,  2.32it/s]
2023-06-15 18:11:07,263 - INFO: Mean validation loss: 0.53028
2023-06-15 18:11:07,273 - INFO: Validation ROC_AUC: 0.82174
2023-06-15 18:11:07,282 - ERROR: Stratified random sampling error: 
Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 195, in resolve
    return self.resolvers[key]
  File "/usr/lib/python3.8/collections/__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.8/collections/__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'class_MG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 206, in resolve
    return self.temps[key]
KeyError: 'class_MG'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hydrogen_torch_cythonized/hydrogen_torch/src/utils/data_utils.py", line 276, in hydrogen_torch.src.utils.data_utils.stratified_sample_indices
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4111, in query
    res = self.eval(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4240, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/eval.py", line 350, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 811, in __init__
    self.terms = self.parse()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 830, in parse
    return self._visitor.visit(self.expr)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 421, in visit_Module
    return self.visit(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 424, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 723, in visit_Compare
    return self.visit(binop)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 549, in visit_Name
    return self.term_type(node.id, self.env, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 98, in __init__
    self._value = self._resolve_name()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 115, in _resolve_name
    res = self.env.resolve(self.local_name, is_local=self.is_local)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 211, in resolve
    raise UndefinedVariableError(key, is_local) from err
pandas.core.computation.ops.UndefinedVariableError: name 'class_MG' is not defined
2023-06-15 18:12:07,863 - INFO: Epoch: 5 / 5
2023-06-15 18:12:07,864 - INFO: train loss:   0%|          | 0/42 [00:00<?, ?it/s]
2023-06-15 18:12:20,539 - INFO: train loss: 0.26:   5%|4         | 2/42 [00:12<04:13,  6.34s/it]
2023-06-15 18:12:21,376 - INFO: train loss: 0.26:  10%|9         | 4/42 [00:13<01:48,  2.86s/it]
2023-06-15 18:12:22,188 - INFO: train loss: 0.27:  14%|#4        | 6/42 [00:14<01:02,  1.74s/it]
2023-06-15 18:12:23,000 - INFO: train loss: 0.26:  19%|#9        | 8/42 [00:15<00:41,  1.21s/it]
2023-06-15 18:12:23,812 - INFO: train loss: 0.26:  24%|##3       | 10/42 [00:15<00:29,  1.09it/s]
2023-06-15 18:12:24,640 - INFO: train loss: 0.26:  29%|##8       | 12/42 [00:16<00:22,  1.34it/s]
2023-06-15 18:12:25,452 - INFO: train loss: 0.26:  33%|###3      | 14/42 [00:17<00:17,  1.57it/s]
2023-06-15 18:12:26,292 - INFO: train loss: 0.26:  38%|###8      | 16/42 [00:18<00:14,  1.76it/s]
2023-06-15 18:12:27,105 - INFO: train loss: 0.26:  43%|####2     | 18/42 [00:19<00:12,  1.93it/s]
2023-06-15 18:12:27,917 - INFO: train loss: 0.26:  48%|####7     | 20/42 [00:20<00:10,  2.07it/s]
2023-06-15 18:12:28,730 - INFO: train loss: 0.26:  52%|#####2    | 22/42 [00:20<00:09,  2.18it/s]
2023-06-15 18:12:29,560 - INFO: train loss: 0.26:  57%|#####7    | 24/42 [00:21<00:08,  2.24it/s]
2023-06-15 18:12:30,395 - INFO: train loss: 0.26:  62%|######1   | 26/42 [00:22<00:06,  2.29it/s]
2023-06-15 18:12:31,216 - INFO: train loss: 0.26:  67%|######6   | 28/42 [00:23<00:06,  2.33it/s]
2023-06-15 18:12:32,029 - INFO: train loss: 0.26:  71%|#######1  | 30/42 [00:24<00:05,  2.37it/s]
2023-06-15 18:12:32,868 - INFO: train loss: 0.26:  76%|#######6  | 32/42 [00:25<00:04,  2.37it/s]
2023-06-15 18:12:33,696 - INFO: train loss: 0.25:  81%|########  | 34/42 [00:25<00:03,  2.39it/s]
2023-06-15 18:12:34,508 - INFO: train loss: 0.26:  86%|########5 | 36/42 [00:26<00:02,  2.41it/s]
2023-06-15 18:12:45,200 - INFO: train loss: 0.26:  90%|######### | 38/42 [00:37<00:07,  1.90s/it]
2023-06-15 18:12:46,010 - INFO: train loss: 0.26:  95%|#########5| 40/42 [00:38<00:02,  1.45s/it]
2023-06-15 18:12:58,851 - INFO: train loss: 0.26:  95%|#########5| 40/42 [00:50<00:02,  1.45s/it]
2023-06-15 18:12:59,842 - INFO: train loss: 0.26: 100%|##########| 42/42 [00:51<00:00,  3.09s/it]
2023-06-15 18:12:59,843 - INFO: train loss: 0.26: 100%|##########| 42/42 [00:51<00:00,  1.24s/it]
2023-06-15 18:12:59,843 - INFO: Starting validation inference
2023-06-15 18:12:59,844 - INFO: validation progress:   0%|          | 0/11 [00:00<?, ?it/s]
2023-06-15 18:13:01,933 - INFO: validation progress:   9%|9         | 1/11 [00:02<00:20,  2.09s/it]
2023-06-15 18:13:02,216 - INFO: validation progress:  18%|#8        | 2/11 [00:02<00:09,  1.03s/it]
2023-06-15 18:13:02,499 - INFO: validation progress:  27%|##7       | 3/11 [00:02<00:05,  1.46it/s]
2023-06-15 18:13:02,783 - INFO: validation progress:  36%|###6      | 4/11 [00:02<00:03,  1.89it/s]
2023-06-15 18:13:03,066 - INFO: validation progress:  45%|####5     | 5/11 [00:03<00:02,  2.27it/s]
2023-06-15 18:13:03,348 - INFO: validation progress:  55%|#####4    | 6/11 [00:03<00:01,  2.59it/s]
2023-06-15 18:13:03,630 - INFO: validation progress:  64%|######3   | 7/11 [00:03<00:01,  2.84it/s]
2023-06-15 18:13:03,912 - INFO: validation progress:  73%|#######2  | 8/11 [00:04<00:00,  3.03it/s]
2023-06-15 18:13:04,195 - INFO: validation progress:  82%|########1 | 9/11 [00:04<00:00,  3.17it/s]
2023-06-15 18:13:04,477 - INFO: validation progress:  91%|######### | 10/11 [00:04<00:00,  3.28it/s]
2023-06-15 18:13:04,657 - INFO: validation progress: 100%|##########| 11/11 [00:04<00:00,  3.75it/s]
2023-06-15 18:13:04,659 - INFO: validation progress: 100%|##########| 11/11 [00:04<00:00,  2.28it/s]
2023-06-15 18:13:04,724 - INFO: Mean validation loss: 0.50892
2023-06-15 18:13:04,733 - INFO: Validation ROC_AUC: 0.76999
2023-06-15 18:13:04,743 - ERROR: Stratified random sampling error: 
Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 195, in resolve
    return self.resolvers[key]
  File "/usr/lib/python3.8/collections/__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.8/collections/__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'class_MG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 206, in resolve
    return self.temps[key]
KeyError: 'class_MG'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hydrogen_torch_cythonized/hydrogen_torch/src/utils/data_utils.py", line 276, in hydrogen_torch.src.utils.data_utils.stratified_sample_indices
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4111, in query
    res = self.eval(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4240, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/eval.py", line 350, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 811, in __init__
    self.terms = self.parse()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 830, in parse
    return self._visitor.visit(self.expr)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 421, in visit_Module
    return self.visit(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 424, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 723, in visit_Compare
    return self.visit(binop)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 549, in visit_Name
    return self.term_type(node.id, self.env, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 98, in __init__
    self._value = self._resolve_name()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 115, in _resolve_name
    res = self.env.resolve(self.local_name, is_local=self.is_local)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 211, in resolve
    raise UndefinedVariableError(key, is_local) from err
pandas.core.computation.ops.UndefinedVariableError: name 'class_MG' is not defined
2023-06-15 18:14:06,549 - INFO: Saving last model checkpoint: val_loss 0.50892, val_ROC_AUC 0.76999 to output/anon/gun_sound_classification.1/fold4/checkpoint.pth
2023-06-15 18:14:06,764 - INFO: Building MLOps and Scoring Pipeline
2023-06-15 18:14:15,119 - INFO: Running interpretability analysis
2023-06-15 18:14:15,124 - ERROR: Stratified random sampling error: 
Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 195, in resolve
    return self.resolvers[key]
  File "/usr/lib/python3.8/collections/__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.8/collections/__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'class_MG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 206, in resolve
    return self.temps[key]
KeyError: 'class_MG'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hydrogen_torch_cythonized/hydrogen_torch/src/utils/data_utils.py", line 276, in hydrogen_torch.src.utils.data_utils.stratified_sample_indices
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4111, in query
    res = self.eval(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4240, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/eval.py", line 350, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 811, in __init__
    self.terms = self.parse()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 830, in parse
    return self._visitor.visit(self.expr)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 421, in visit_Module
    return self.visit(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 424, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 723, in visit_Compare
    return self.visit(binop)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 549, in visit_Name
    return self.term_type(node.id, self.env, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 98, in __init__
    self._value = self._resolve_name()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 115, in _resolve_name
    res = self.env.resolve(self.local_name, is_local=self.is_local)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 211, in resolve
    raise UndefinedVariableError(key, is_local) from err
pandas.core.computation.ops.UndefinedVariableError: name 'class_MG' is not defined
2023-06-15 18:14:17,045 - WARNING: Interpretation is not supported for the current model architecture
